export const AuditActions = {

    LOGIN: "LOGIN",

    REGISTER: "REGISTER",

    CREATE_CLUB: "CREATE_CLUB",

    UPDATE_CLUB: "UPDATE_CLUB",

    VERIFY_CLUB: "VERIFY_CLUB",
    DELETE_ATHLETE: "DELETE_ATHLETE",

    VERIFY_FAYDA: "VERIFY_FAYDA",

    ASSIGN_ROLE: "ASSIGN_ROLE",

    CREATE_COMPETITION: "CREATE_COMPETITION",
    CLUB_REGISTERED: "CLUB_REGISTERED",
    CLUB_APPROVED: "CLUB_APPROVED",
    CLUB_REJECTED: "CLUB_REJECTED",
    CLUB_SUSPENDED: "CLUB_SUSPENDED",

    FAYDA_VERIFY_INITIATED: "FAYDA_VERIFY_INITIATED",
    FAYDA_VERIFY_CONFIRMED: "FAYDA_VERIFY_CONFIRMED",

    APPROVE_ATHLETE: "APPROVE_ATHLETE",
    REJECT_ATHLETE: "REJECT_ATHLETE",
    ACTIVATE_ATHLETE: "ACTIVATE_ATHLETE",
    SUSPEND_ATHLETE: "SUSPEND_ATHLETE",
    APPROVE_COACH: "APPROVE_COACH",
    REJECT_COACH: "REJECT_COACH",
    ACTIVATE_COACH: "ACTIVATE_COACH",
    SUSPEND_COACH: "SUSPEND_COACH",
    ACTIVATE_USER: "ACTIVATE_USER",
    DEACTIVATE_USER: "DEACTIVATE_USER",

} as const;