export const AuditActions = {

    LOGIN: "LOGIN",

    REGISTER: "REGISTER",

    CREATE_CLUB: "CREATE_CLUB",

    UPDATE_CLUB: "UPDATE_CLUB",

    VERIFY_CLUB: "VERIFY_CLUB",
    DELETE_ATHLETE: "DELETE_ATHLETE",

    VERIFY_FAYDA: "VERIFY_FAYDA",

    ASSIGN_ROLE: "ASSIGN_ROLE",

    CREATE_COMPETITION: "CREATE_COMPETITION",
    CLUB_REGISTERED: "CLUB_REGISTERED",
    CLUB_APPROVED: "CLUB_APPROVED",
    CLUB_REJECTED: "CLUB_REJECTED",
    CLUB_SUSPENDED: "CLUB_SUSPENDED",

    FAYDA_VERIFY_INITIATED: "FAYDA_VERIFY_INITIATED",
    FAYDA_VERIFY_CONFIRMED: "FAYDA_VERIFY_CONFIRMED",

    APPROVE_ATHLETE: "APPROVE_ATHLETE",
    REJECT_ATHLETE: "REJECT_ATHLETE",
    ACTIVATE_ATHLETE: "ACTIVATE_ATHLETE",
    SUSPEND_ATHLETE: "SUSPEND_ATHLETE",
    APPROVE_COACH: "APPROVE_COACH",
    REJECT_COACH: "REJECT_COACH",
    ACTIVATE_COACH: "ACTIVATE_COACH",
    SUSPEND_COACH: "SUSPEND_COACH",
    ACTIVATE_USER: "ACTIVATE_USER",
    DEACTIVATE_USER: "DEACTIVATE_USER",

    CREATE_EVENT: "CREATE_EVENT",
    SUBMIT_EVENT_FOR_APPROVAL: "SUBMIT_EVENT_FOR_APPROVAL",
    APPROVE_EVENT: "APPROVE_EVENT",
    REJECT_EVENT: "REJECT_EVENT",
    OVERRIDE_EVENT_STATUS: "OVERRIDE_EVENT_STATUS",

    CREATE_POLICY: "CREATE_POLICY",
    UPDATE_POLICY: "UPDATE_POLICY",
    ASSIGN_POLICY: "ASSIGN_POLICY",
    UNASSIGN_POLICY: "UNASSIGN_POLICY",

    GENERATE_EVENT_QR_TOKEN: "GENERATE_EVENT_QR_TOKEN",
    VERIFY_EVENT_QR_CHECK_IN: "VERIFY_EVENT_QR_CHECK_IN",

    CREATE_PAYMENT: "CREATE_PAYMENT",
    VERIFY_PAYMENT: "VERIFY_PAYMENT",
    PAYMENT_WEBHOOK_RECEIVED: "PAYMENT_WEBHOOK_RECEIVED",

    LOGOUT: "LOGOUT",
    // Applications Review
    REVIEW_APPLICATION: "REVIEW_APPLICATION",

    // Competition Results
    CREATE_COMPETITION_RESULTS: "CREATE_COMPETITION_RESULTS",
    PUBLISH_COMPETITION_RESULTS: "PUBLISH_COMPETITION_RESULTS",

    // Staff Administration
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",

    // Entity Updates
    UPDATE_EVENT: "UPDATE_EVENT",
    ISSUE_ATHLETE_PENALTY: "ISSUE_ATHLETE_PENALTY",

    // Analytics
    VIEW_DASHBOARD_ANALYTICS: "VIEW_DASHBOARD_ANALYTICS",

    TOKEN_REFRESH: "TOKEN_REFRESH",

} as const;
