export const AuditActions = {

    LOGIN: "LOGIN",

    REGISTER: "REGISTER",

    CREATE_CLUB: "CREATE_CLUB",

    UPDATE_CLUB: "UPDATE_CLUB",

    VERIFY_CLUB: "VERIFY_CLUB",
    DELETE_ATHLETE: "DELETE_ATHLETE",

    VERIFY_FAYDA: "VERIFY_FAYDA",

    ASSIGN_ROLE: "ASSIGN_ROLE",

    CREATE_COMPETITION: "CREATE_COMPETITION",

} as const;